### ISSUE TITLE
Can't find Class CodeIgniter_Sniffs_Files_AbstractClosingCommentSniff 

### ISSUE THREAD

**Issue by deadtrickster** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#1]
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Class CodeIgniter_Sniffs_Files_AbstractClosingCommentSniff not found in /usr/share/php/PHP/CodeSniffer.php on line 462
#0 /usr/share/php/PHP/CodeSniffer.php(462): include_once()
#1 /usr/share/php/PHP/CodeSniffer.php(494): PHP_CodeSniffer->getTokenListeners('CodeIgniter', Array)
#2 /usr/share/php/PHP/CodeSniffer.php(357): PHP_CodeSniffer->setTokenListeners('CodeIgniter', Array)
#3 /usr/share/php/PHP/CodeSniffer/CLI.php(423): PHP_CodeSniffer->process(Array, 'CodeIgniter', Array, false)
#4 /usr/bin/phpcs(30): PHP_CodeSniffer_CLI->process()
#5 {main}

  thrown in /home/dead/Projects/General/CodeIgniter/CodeSniffer/Sniffs/Files/ClosingLocationCommentSniff.php on line 17

**Comment by thomas-ernest** [comment]
I missed this file for my last commit.
I'll fix that in next days, when I'll have access to my source code again.
Sorry for the delay.

**Comment by deadtrickster** [comment]
yeah, just created empty definition for myself :-). Also there're some questions

1) How to get it working with symbolic links? I want to keep this standard in one of my Project subdirs and still able be using the short parameter --standard so I create ln -s in /usr/share.... but class loading isn't working (

2) this one is Very frustrating - imagine you have controller named Test in file test.php.And here it goes to hell - standard emits error that says that file must be named after class. ok, I renamed it to class test. And now it says that class name must start with capital letter. The only solution here is to name the file as Test which is not the case for me because it requires the Shift key to be pressed, but I feel myself too lazy for that )

Hope you will help )

**Comment by thomas-ernest** [comment]
I guess the empty definition is an good temporary workaround since I already developped the code :-)

1) I don't know. I haven't tried such thing ;-). Did you try to change PHP include path or something similar to get ride of this problem ?

2) My mistake. File names should be only lower-cased and class names should have their first letter upper-cased only. I use Squiz/Sniffs/Classes/ClassFileNameSniff.php to ensures file naming. However, it's case sensitive. Hence, there is the error that you explained.
It wasn't specified in CodeIgniter coding convention that is why I noticed it so late. Can you create a ticket about this error, so that I'll remember to fix it. In waiting the fix, to avoid this error you should deactivate the Sniff :
A/ for PHP_CodeSniffer earlier to version 1.3.0, in commenting the line containing "Squiz/Sniffs/Classes/ClassFileNameSniff.php" in file CodeIgniterCodingStandard.php [1].
B/ as for PHP_CodeSniffer 1.3.0. in commenting line containing <rule ref="Squiz.Classes.ClassFileName"/> in ruleset.xml [2]

Hope that help :-)

[1] https://github.com/thomas-ernest/CodeIgniter-for-PHP_CodeSniffer/blob/master/CodeIgniterCodingStandard.php
[2] https://github.com/thomas-ernest/CodeIgniter-for-PHP_CodeSniffer/blob/master/ruleset.xml

**Comment by thomas-ernest** [comment]
It should be fixed also. Can you tell me, if it works on your setup please, so that I close the issue please ?

Thanks a lot for your reviews. Please keep reporting bug that way, so that we improve this project.

Cheers.

**Comment by thomas-ernest** [comment]
Fixed with commit e3fa525e7460735133f56aa8e6cb8687f39a6d88 available at https://github.com/thomas-ernest/CodeIgniter-for-PHP_CodeSniffer/commit/e3fa525e7460735133f56aa8e6cb8687f39a6d88 .
