### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class CodeIgniter_Sniffs_Strings_VariableUsageSniff

### ISSUE THREAD

**Issue by titosemi** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#12]
Hi, 

first of all, i want to thank you for this. I think it's a really good idea to have this rules so we all can follow the Codeigniter's coding styles.

I'm getting this error:
PHP Fatal error:  Cannot redeclare class CodeIgniter_Sniffs_Strings_VariableUsageSniff in CodeSniffer/Standards/codeigniter/Sniffs/Strings/VariableUsageSniff.php on line 30 when using the rules within Netbeans

Any idea what could be the problem?

**Comment by jimCresswell** [comment]
Hi,

Have you tried changing the name of your class to match the case of your directory structure? I.e. changing the class name to codeigniter_Sniffs_Strings_VariableUsageSniff with a lower case c and i in codeigniter.

Cheers,

Jim

**Comment by dmp1ce** [comment]
I had a similar problem when setting up the Symfony2 code standards.  For me the problem was that I symlinked a folder into the /usr/share/php/PHP/CodeSniffer/Standards directory wrong.  The original directory was called something like "Symfony2-Code-Standards" but the symlink was called "Symfony2".  Renaming the "Symfony2-Code-Standards" directory to "Symfony2" fixed my problem.
